services:
  - type: web
    name: trello-clone
    env: static
    buildCommand: pnpm install && pnpm build && chmod +x .output/server/index.mjs
    staticPublishPath: .output/public
    startCommand: node .output/server/index.mjs
    envVars:
      - key: NITRO_PRESET
        value: render